### ISSUE TITLE
Add pre-commit hooks and GitHub actions for formatting.

### ISSUE THREAD

**Issue by kappq** [OpenSourceSimon/TheTechMorningNewspaper#4]
The idea would be to add pre-commit hooks and GitHub actions activated when there are new commits to the master branch, to make sure that the code style is clean and consistent.
I would add `black` (for formatting) and `isort` (for sorting imports).
Any additional plugins/ideas can be discussed below.

**Comment by OpenSourceSimon** [comment]
Good idea!
